config/routes.rb
Rails.application.routes.draw do
  get 'contact/list'
  root 'contact#list'
  resources :conversations, only: [:index, :create] do 
  	member do 
  		post 'new_message'
  	end
  end
  devise_for :users 
  mount ActionCable.server => "/cable"

  resources :messages, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_model.rb
class ApplicationModel
	require 'autoinc'
  include Mongoid::Document
  include Mongoid::Autoinc
  include Mongoid::Timestamps

end

app/models/block_list.rb
class BlockList
	include Common
  field :key, type: Integer
  increments :key  
  belongs_to :user
  belongs_to :participate
end

app/models/concerns/common.rb
module Common

	require 'autoinc'

	extend ActiveSupport::Concern
	included do
	  include Mongoid::Document
	  include Mongoid::Autoinc
	  include Mongoid::Timestamps
	  include Mongoid::Attributes::Dynamic
	end
end

app/models/conversation.rb
class Conversation
	include Common
  field :title, type: String
  field :deleted_at, type: Time
  field :key, type: Integer
  increments :key
  belongs_to :user
  has_many :participators, class_name: 'Participate', dependent: :destroy
  has_many	:messages, class_name: 'Message', dependent: :destroy	
  # embeds_many :participates, cascade_callbacks: true
end

app/models/delete_conversation.rb
class DeleteConversation
	include Common
  field :key, type: Integer
  increments :key
  belongs_to :conversation
  belongs_to :user
end

app/models/delete_message.rb
class DeleteMessage
	include Common
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message
  include Common
  field :message_type, type: String
  field :content, type: String
  field :read, type: Mongoid::Boolean
  field :deleted_at, type: Time
  field :key, type: Integer
  increments :key
  belongs_to :conversation, class_name: 'Conversation'
  belongs_to :sender, class_name: 'User'
  # after_create :broadcast_message

  def receivers
      User.in(id: conversation.participators.pluck(:user_id).map(&:to_s)).all.entries
  end

end
	

app/models/participate.rb
class Participate
	include Common
  field :key, type: Integer
  increments :key
  field :type, type: String, default: 'Single'
  belongs_to :conversation
  belongs_to :user
end

app/models/user.rb
class User
  include Common
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  field :key, type: Integer
  increments :key         

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  # custom fields
  field :name,     type: String
  field :avatar,     type: String
  field :phone,    type: Integer
  field :is_block, type: Mongoid::Boolean, default: false
  field :is_active, type: Mongoid::Boolean, default: true
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field :deleted_at, type: Time
  has_many :conversations, dependent: :destroy
  has_many :messages, foreign_key: 'sender_id', dependent: :destroy
  has_many :participates, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	before_action :authenticate_user!
  def list
  	@users = User.not_in(_id:[ current_user.id])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy, :new_message]
  before_action :authenticate_user!
  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.in(id: current_user.participates.pluck(:conversation_id).map(&:to_s)).all.entries
    @conversations = @conversations | current_user.conversations.all.entries
    if params[:id].present?
      @conversation = Conversation.find({id: params[:id]})
    else

      id = Message.last.conversation_id
      @conversation = Conversation.find({id: id}) if id.present?
      @conversation = Conversation.last if @conversation.nil?
    end
    @messages = @conversation&.messages
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  def new_message
    @message = current_user.messages.new(message_params)
    @message.save

    SendMessageJob.perform_later(@message.id.to_s)
     
     respond_to do |format|
      format.js
     end
  end

  def broadcast_message

    ApplicationController.renderer.instance_variable_set(:@env, {"HTTP_HOST"=>"localhost:2300", 
      "HTTPS"=>"off", 
      "REQUEST_METHOD"=>"GET", 
      "SCRIPT_NAME"=>"",   
      "warden" => warden}
    )

    html = ApplicationController.render(
      partial: 'conversations/messages',
      locals: { messages: @conversation.messages.entries.last(5) }
    )
    
    
     ActionCable.server.broadcast(
        "conversation_channel_#{@conversation.id.to_s}",
        sender_id: @message.sender_id.to_s,
        receiver_ids: @conversation.participators.pluck(:id).map(&:to_s),
        html: html,
        created_at: @message.created_at.localtime.strftime('%I:%M %p | %b %e')
      )   
  end  

  # POST /conversations
  # POST /conversations.json
  def create
    participates1 = current_user.participates.pluck(:conversation_id).map(&:to_s)
    participates2 = User.find(id: params[:user_id]).participates.pluck(:conversation_id).map(&:to_s)
    common = participates1 & participates2
    if common.empty?
      @conversation = current_user.conversations.create!(title: 'Personal')
      Participate.create!(conversation_id: @conversation.id, user_id: current_user.id)
      Participate.create!(conversation_id: @conversation.id, user_id: params[:user_id])
    else
      @conversation = Conversation.find(id: common[0])
    end
    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversations_path(id: @conversation.id) }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find({id: params[:id]})
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:title)
    end

    def message_params
      params.require(:message).permit(:conversation_id, :content)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper

	def last_message_sender(conversation)
		 Message.where({conversation_id: conversation.id}).order(created_at: :asc).last
	end
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/contact/list.html.erb
<br>
    <!-- contacts card -->
    <div class="card card-default" id="card_contacts">
        <div id="contacts" class="panel-collapse collapse show" aria-expanded="true" style="">
            <ul class="list-group pull-down" id="contact-list">
            		<% @users.each do |user| %>
	                <li class="list-group-item">
	                    <div class="row w-100">
	                        <div class="col-12 col-sm-6 col-md-3 px-0">
	                            <img src="<%= user.avatar.url%>" alt="Mike Anamendolla" class="rounded-circle mx-auto d-block img-fluid">
	                        </div>
	                        <div class="col-12 col-sm-6 col-md-9 text-center text-sm-left">
                            <a href="/conversations?user_id=<%= user.id%>" data-method='post'><span class="fa fa-envelope fa-lg text-danger float-right" title="left you a message"></span></a>
	                          

	                            <label class="name lead"><%= user.name %></label>
	                            <br>
	                            <span class="fa fa-phone fa-fw text-muted" data-toggle="tooltip" title="" data-original-title="(870) 288-4149"></span>
	                            <span class="text-muted small">(+91) <%= user.phone %></span>
	                            <br>
	                            <span class="fa fa-envelope fa-fw text-muted" data-toggle="tooltip" data-original-title="" title=""></span>
	                            <span class="text-muted small text-truncate"> <%= user.email %></span>
	                        </div>
	                    </div>
	                </li>
                <% end %>
            </ul>
            <!--/contacts list-->
        </div>
    </div>

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/_me.html.erb
	<div class="outgoing_msg">
	  <div class="sent_msg">
	    <p><%= message.content%></p>
	    <span class="time_date"><%= message.created_at.localtime.strftime('%I:%M %p | %b %e')%> </span></div>
	</div>

app/views/conversations/_messages.html.erb
<%messages&.each do |message|%>
	<% if message.sender.id == current_user.id %>
	<div class="outgoing_msg">
	  <div class="sent_msg">
	    <p><%= message.content%></p>
	    <span class="time_date"><%= message.created_at.localtime.strftime('%I:%M %p | %b %e')%> </span></div>
	</div>
	<%else%>
	  <div class="incoming_msg">
	      <div class="incoming_msg_img"><%= image_tag message.sender.avatar.url, class: 'rounded-circle'%></div>
	        <div class="received_msg">
	          <div class="received_withd_msg">
	            <p><%= message.content%></p>
	            <span class="time_date"><%= message.created_at.localtime.strftime('%I:%M %p | %b %e')%> </span></div>
	      </div>
	  </div>              
	<%end%>

<%end%>

app/views/conversations/_recent_message.html.erb
	<h5><%= other_user&.name %> </h5>	
	<% if message.nil?%>
	<%else%>
		<span class="chat_date"><%= message.present? ?  time_ago_in_words(message&.created_at, include_seconds: true) : '-'%></span></h5>	
	<p><%= message&.content %></p>
	<%end%>

app/views/conversations/_theirs.html.erb
<div class="incoming_msg">
  <div class="incoming_msg_img"><%= image_tag message.sender.avatar.url%> </div>
    <div class="received_msg">
      <div class="received_withd_msg">
        <p><%= message.content%></p>
        <span class="time_date"><%= message.created_at.localtime.strftime('%I:%M %p | %b %e')%> </span></div>
  </div>
</div>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<div id="conversation-id" data-conversation-id="<%= @conversation&.id%>" ></div>
<div id="conversation-ids" data-conversation-ids="<%= raw @conversations.map { |c| c.id.to_s}.join(',') %>" ></div>

<h3 class=" text-center">Messaging</h3>
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Recent</h4>
            </div>
            <div class="srch_bar">
              <div class="stylish-input-group">
                <input type="text" class="search-bar"  placeholder="Search" >
                <span class="input-group-addon">
                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span> </div>
            </div>
          </div>
          <div class="inbox_chat">

            <%@conversations.each_with_index do |conversation, index|%>
                <% klass = @conversation.id == conversation.id ? 'active_chat' : '' %>
                <a href="/conversations?id=<%= conversation.id.to_s%>">
                <div class="chat_list  <%= klass %>">

                      <% message = last_message_sender(conversation)%>
                      <div class="chat_people">
              
                        <div class="chat_img">
                          <%other_user = conversation.participators&.not_in(user_id: current_user.id)&.last&.user %>
                          <%= image_tag other_user&.avatar&.url,  class: 'rounded-circle'%>
                        </div>
                    <%#if @conversation.id == conversation.id %>
                      <div class="chat_ib" id="<%=dom_id(conversation)%>">
                        <%= render 'conversations/recent_message', message: message, other_user: other_user %>
                      </div>
                    <%#end%>
                  </div>
                </div>
              </a>
            <%end%>

          </div>
        </div>
        <div class="mesgs">
          <div class="msg_history" id="conversations-<%= @conversations.id%>">
             <%= render 'conversations/messages', messages: @messages %>
          </div>
          <div class="type_msg">
            <div class="input_msg_write">

              <input type="text" class="write_msg" placeholder="Type a message" name="message[content]" />
              <button id="new-message" class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>

            </div>
          </div>
        </div>
      </div>
      
      
      <p class="text-center top_spac"> Design by <a target="_blank" href="#">Ankur Saini</a></p>
      
    </div>
  
  <script type="text/javascript">

    $(window).on('load', function(){
      var getTopOffset = $('.msg_history').prop("scrollHeight")
      $('.msg_history').animate({scrollTop: getTopOffset},500)
    })

    $(document).ready(function(){

      $('#new-message').click(function(){
        const room_element = document.getElementById('conversation-id');
        const conversation_id = room_element.getAttribute('data-conversation-id');
        $.ajax({
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          type:"POST",
          url: `/conversations/${conversation_id}/new_message`,
          data: {"[message][content]": $('.write_msg').val(), 'message[conversation_id]': conversation_id }
        })
      })



      // Execute a function when the user releases a key on the keyboard
      document.addEventListener("keyup", function(event) {
        // Number 13 is the "Enter" key on the keyboard
        if (event.keyCode === 13) {
          // Cancel the default action, if needed
          event.preventDefault();
          // Trigger the button element with a click
          document.getElementById("new-message").click();
        }
      });      
    })
  </script>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/new_message.js.erb
$(".write_msg").val('')

var getTopOffset = $('.msg_history').prop("scrollHeight")
$('.msg_history').animate({scrollTop: getTopOffset},500)

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @conversation.index %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div id="user-id" data-user-id="<%= current_user.id %>"></div>
    <h3><%= current_user.name%></h3>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>     
    <a href="/contact/list">Contacts</a>   

  <% else %>

    <%= link_to('Login', new_user_session_path) %>  

  <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>